version: '3.8'

services:
  smart-investment-backend:
    build: .
    ports:
      - "8006:8006"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/api/dashboard/1"]
      interval: 30s
      timeout: 10s
      retries: 3

  smart-investment-frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - brain-health-backend